- .travis.yml
- README.md
- src/dns_server/mod.rs
- src/dns_server/setup.rs
- src/main.rs
- src/tun/mod.rs
- src/tun/phy/mod.rs
- src/tun/phy/sys/mod.rs
- src/tun/phy/sys/tun_darwin.rs
- src/tun/phy/sys/tun_linux.rs
> support Linux

- Cargo.lock
- README.md
- seeker/src/client.rs
- seeker/src/main.rs
- sysconfig/Cargo.toml
- sysconfig/src/lib.rs
- sysconfig/src/proc/darwin.rs
- sysconfig/src/proc/linux.rs
- sysconfig/src/proc/mod.rs
> Allow proxy one single user

- Cargo.lock
- README.md
- config/src/lib.rs
- config/src/server_config.rs
- hermes/hermesdns/Cargo.toml
- hermes/hermesdns/src/dns/client.rs
- hermes/hermesdns/src/dns/protocol.rs
- sample_config.yml
- seeker/src/main.rs
- ssclient/Cargo.toml
- ssclient/src/connection_pool.rs
- ssclient/src/encrypted_stream/aead_encrypt.rs
- ssclient/src/encrypted_stream/mod.rs
- ssclient/src/encrypted_stream/stream_encrypt.rs
- ssclient/src/lib.rs
- ssclient/src/tcp_io.rs
- ssclient/src/udp_io.rs
- sysconfig/src/lib.rs
- sysconfig/src/net/darwin.rs
- sysconfig/src/net/linux.rs
- sysconfig/src/net/mod.rs
- tun/src/lib.rs
* 使用连接池连接 ss 服务器，连接池内会一直保留一定数量握手完成的连接
* 增加网关模式，可以为局域网内机器代理
> Add Connection Pool && Add Gateway Mode

- Cargo.lock
- hermes/hermesdns/src/dns/client.rs
- seeker/src/client.rs
- ssclient/Cargo.toml
- ssclient/src/connection_pool.rs
- ssclient/src/encrypted_stream/aead_encrypt.rs
- ssclient/src/encrypted_stream/stream_encrypt.rs
- ssclient/src/lib.rs
Auto failover is not working in #25 . This PR fixed it.
> Fix failover

- Cargo.lock
- config/Cargo.toml
- seeker/Cargo.toml
- ssclient/Cargo.toml
- ssclient/src/lib.rs
- tun/Cargo.toml
@ficapy 这个PR合并后就可以用 musl build 了
> upgrade smoltcp to allow build under musl

- dnsserver/src/resolver.rs
- hermes/hermesdns/src/dns/client.rs
- hermes/hermesdns/src/hosts.rs
- hermes/hermesdns/src/lib.rs
> dns server respect /etc/hosts

- Cargo.lock
- seeker/src/client/direct_client.rs
- seeker/src/client/ruled_client.rs
- ssclient/Cargo.toml
- ssclient/src/client_stats.rs
- ssclient/src/lib.rs
> track sent & recv bytes

- Cargo.lock
- dnsserver/Cargo.toml
- hermes/Cargo.toml
- hermes/hermesdns/Cargo.toml
- seeker/Cargo.toml
- ssclient/Cargo.toml
- tun/Cargo.toml
This should reduce some cpu consumption.
> bump async-std version

- Cargo.lock
- LICENSE-APACHE
- LICENSE-MIT
- README.md
- config/src/lib.rs
- config/src/server_config.rs
- sample_config.yml
- seeker/Cargo.toml
- seeker/src/client.rs
- seeker/src/client/direct_client.rs
- seeker/src/client/ruled_client.rs
- seeker/src/client/shadowsocks_client.rs
- seeker/src/client/socks5_client.rs
- ssclient/src/connection_pool.rs
- ssclient/src/encrypted_stream/aead_encrypt.rs
- ssclient/src/encrypted_stream/stream_encrypt.rs
- ssclient/src/lib.rs
resolved #48 
socks5 模式目前不支持 UDP
> add support for socks5 server， tcp only

- README.md
- config/src/lib.rs
- dnsserver/src/lib.rs
- dnsserver/src/resolver.rs
- sample_config.yml
- seeker/src/client/ruled_client.rs
- seeker/src/main.rs
- socks5_client/examples/udp_echo.rs
> allow  set only one of shadowsocks_servers and socks5_server

- tun/src/lib.rs
- tun/src/socket/tcp_socket.rs
- tun/src/socket/udp_socket.rs
> Lock with timeout

- Cargo.lock
- dnsserver/Cargo.toml
- hermes/Cargo.toml
- hermes/hermesdns/Cargo.toml
- seeker/Cargo.toml
- socks5_client/Cargo.toml
- ssclient/Cargo.toml
- tun/Cargo.toml
下载 7MB/s 的时候重试一次 CPU 占 100%，去掉重试 CPU 在 30% ～ 40% 之间波动
https://github.com/gfreezy/async-std/commit/fb8866c5b300d76d6b03234e4145096ee62d56db
> async-std reactor blocking 的时候不再重试

- seeker/src/macros.rs
- seeker/src/proxy_client.rs
- seeker/src/server_chooser.rs
- ssclient/src/tcp_io.rs
* 某一个 server 超时的时候，自动将所有这个 server 的 tcp 链接全部断开
* server 超时的时候自动切换到下一个 server
> 某一个 host 超时自动恢复

- seeker/src/main.rs
> use dns from config

- README.adoc
- config/src/lib.rs
- dnsserver/src/lib.rs
- dnsserver/src/resolver.rs
- sample_config.yml
- seeker/src/dns_client.rs
- seeker/src/proxy_client.rs
配置文件发生了变动
`dns_server` 改成了 `dns_servers` ，从 string 变成了 list 类型
> 支持多个 dns server

- Cargo.lock
- README.adoc
- config/Cargo.toml
- config/src/lib.rs
- config/src/server_config.rs
- sample_config.yml
- seeker/src/dns_client.rs
> dns server adds tcp support

- seeker/src/proxy_tcp_stream.rs
- seeker/src/server_chooser.rs
- seeker/src/traffic.rs
As below:
```
Connections:
optimizationguide-pa.googleapis.com:443, conns: 1, sent_bytes: 2836, recv_bytes: 3896
mon.zijieapi.com:443, conns: 2, sent_bytes: 13254, recv_bytes: 12713
mobile.events.data.microsoft.com:443, conns: 1, sent_bytes: 1505, recv_bytes: 4932
adservice.google.com:443, conns: 1, sent_bytes: 1771, recv_bytes: 1939
jnn-pa.googleapis.com:443, conns: 1, sent_bytes: 6349, recv_bytes: 97231
gateway.reddit.com:443, conns: 1, sent_bytes: 2627, recv_bytes: 534644
aa.google.com:443, conns: 1, sent_bytes: 2875, recv_bytes: 48818
pagead2.googlesyndication.com:443, conns: 2, sent_bytes: 4052, recv_bytes: 14848
yt3.ggpht.com:443, conns: 1, sent_bytes: 1365, recv_bytes: 4408
imap.gmail.com:993, conns: 4, sent_bytes: 6020, recv_bytes: 27543
www.google.com:443, conns: 1, sent_bytes: …
```
> stats include connection stats

- Cargo.lock
- config/src/lib.rs
- hermesdns/src/dns/protocol.rs
- seeker/src/server_chooser.rs
- tcp_connection/Cargo.toml
- tcp_connection/src/lib.rs
- tcp_connection/src/obfs_http.rs
- tun_nat/src/lib.rs
use simple-obfs docker to test obfs client
> add test for obfs http

- config/src/lib.rs
- config/src/rule.rs
- http_proxy_client/src/https.rs
- seeker/src/proxy_tcp_stream.rs
- tcp_connection/src/lib.rs
- tcp_connection/src/obfs_http.rs
- tcp_connection/src/obfs_tls.rs
- 修改了部分参数从String -> &str, 减少内存复制
- 参考go版实现了tls(未测试)
> fix: #119 impl tls obfs and some clippy

- config/src/lib.rs
- seeker/src/main.rs
- seeker/src/proxy_client.rs
> fix ip route
